//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TratamientoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TratamientoDetalle()
        {
            this.TratamientoDetalleMedicamento = new HashSet<TratamientoDetalleMedicamento>();
        }
    
        public int idTratamientoDetalle { get; set; }
        public int idTratamiento { get; set; }
        public string sintomas { get; set; }
        public string diagnosticoParcial { get; set; }
        public Nullable<int> idMedicamento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Tratamiento Tratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TratamientoDetalleMedicamento> TratamientoDetalleMedicamento { get; set; }
    }
}
