//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int idTurno { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string detalles { get; set; }
        public int idPaciente { get; set; }
        public int idMedico { get; set; }
        public string estado { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
